name: Deploy React App to GitHub Pages

on:
  push:
    branches:
      - main  # Deploy whenever you push to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repository
      - name: Checkout source code
        uses: actions/checkout@v3
        with:
          persist-credentials: false  # Allow custom token usage

      # Step 2: Setup Node.js environment
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm install

      # Step 4: Build the React project
      - name: Build project
        run: npm run build

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build
          keep_files: false   # Optional: remove old files in gh-pages
          commit_message: "Deploy React App to GitHub Pages"
